from models.common import db

class Endsem_details(db.Model):
	theclass = db.Column(db.String, db.ForeignKey("classes.theclass"), primary_key = True)
	subject = db.Column(db.String, db.ForeignKey("subjects.subject"), primary_key = True)
	d1 = db.Column(db.Integer)
	co1 = db.Column(db.Integer)
	d2 = db.Column(db.Integer)
	co2 = db.Column(db.Integer)
	d3 = db.Column(db.Integer)
	co3 = db.Column(db.Integer)
	d4 = db.Column(db.Integer)
	co4 = db.Column(db.Integer)
	d5 = db.Column(db.Integer)
	co5 = db.Column(db.Integer)
	d6 = db.Column(db.Integer)
	co6 = db.Column(db.Integer)
	d7 = db.Column(db.Integer)
	co7 = db.Column(db.Integer)
	d8 = db.Column(db.Integer)
	co8 = db.Column(db.Integer)
	d9 = db.Column(db.Integer)
	co9 = db.Column(db.Integer)
	d10 = db.Column(db.Integer)
	co10 = db.Column(db.Integer)
	d11 = db.Column(db.Integer)
	co11 = db.Column(db.Integer)
	d12 = db.Column(db.Integer)
	co12 = db.Column(db.Integer)
	d13 = db.Column(db.Integer)
	co13 = db.Column(db.Integer)
	d14 = db.Column(db.Integer)
	co14 = db.Column(db.Integer)
	d15 = db.Column(db.Integer)
	co15 = db.Column(db.Integer)
	d16 = db.Column(db.Integer)
	co16 = db.Column(db.Integer)
	d17 = db.Column(db.Integer)
	co17 = db.Column(db.Integer)
	d18 = db.Column(db.Integer)
	co18 = db.Column(db.Integer)
	d19 = db.Column(db.Integer)
	co19 = db.Column(db.Integer)
	d20 = db.Column(db.Integer)
	co20 = db.Column(db.Integer)