from models.common import db

class Endsem(db.Model):
	uid = db.Column(db.String, db.ForeignKey("students.uid"), primary_key = True)
	subject = db.Column(db.String, db.ForeignKey("subjects.subject"), primary_key = True)
	q1 = db.Column(db.Float, default = 0)
	q2 = db.Column(db.Float, default = 0)
	q3 = db.Column(db.Float, default = 0)
	q4 = db.Column(db.Float, default = 0)
	q5 = db.Column(db.Float, default = 0)
	q6 = db.Column(db.Float, default = 0)
	q7 = db.Column(db.Float, default = 0)
	q8 = db.Column(db.Float, default = 0)
	q9 = db.Column(db.Float, default = 0)
	q10 = db.Column(db.Float, default = 0)
	q11 = db.Column(db.Float, default = 0)
	q12 = db.Column(db.Float, default = 0)
	q13 = db.Column(db.Float, default = 0)
	q14 = db.Column(db.Float, default = 0)
	q15 = db.Column(db.Float, default = 0)
	q16 = db.Column(db.Float, default = 0)
	q17 = db.Column(db.Float, default = 0)
	q18 = db.Column(db.Float, default = 0)
	q19 = db.Column(db.Float, default = 0)
	q20 = db.Column(db.Float, default = 0)